config/routes.rb
Blog::Application.routes.draw do
  

  root :to => "posts#index"
  resources :users

  	resources :posts do
  		resources :comments
	end

   match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
	has_many :posts
	validates_presence_of :login, :password
  # attr_accessor :hashed_password
	
	# validates_length_of :password, :within => 8..25, :on => :create
	
	before_save :create_hashed_password
	after_save :clear_password
	
	# attr_protected  :password, :salt
	
	def self.authenticate(login="", password="")
	  user = User.find_by_login(login)
	  if user && user.password == User.hash_with_salt(password, User.make_salt(login))
	    return user
	  else
	    return false
	  end
	  # return user
	end
	
	def password_match?(hashed_password="")
	  password == User.hash_with_salt(hashed_password, salt)
	end
	
	def self.make_salt(login="")
	  # Digest::SHA1.hexdigest("Use #{login} with #{Time.now} to make salt")
	  Digest::SHA1.hexdigest("Use #{login} to make salt")
	end

  def self.hash_with_salt(password="", salt="")
    Digest::SHA1.hexdigest("Put #{salt} on the #{password}")
  end
  
  private
 
  def create_hashed_password
    unless password.blank?
      self.salt = User.make_salt(login) if salt.blank?
      self.password = User.hash_with_salt(password, salt)
    end
  end
  
  def clear_password
    self.password= nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  
  before_filter :confirm_logged_in, :except => [:create, :new]
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    @posts = @user.posts

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password, "Hasło"%><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Zapisz"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="user_content">

<h1>Edytuj użytkownika</h1>

<%= render 'form' %>
<%= link_to 'Powrót', @user %>
<!-- <%= link_to 'Back', users_path %> -->

</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Login</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.login %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="user_content">
<h1>Nowy użytkownik</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div id="user_content">

	<h1><%= @user.login %></h1>
	<p id="notice">
		<%= notice %>
	</p>
	<!-- <p>
	<b>Password:</b>
	<%= @user.password %>
	</p> -->

	<%= link_to 'Edytuj swój profil', edit_user_path(@user) %> | 
	<%= link_to 'Nowy artykół', new_post_path %> | 
	<%= link_to "wyloguj", :controller => "access", :action => "logout"%> 
	<br/><br/>
	<h2>Twoje artykuły</h2>
	<div id="post">
		<% @posts.each do |i|%>
		<p>
			<span id="post_title">
				<br/>
				<%= i.title%> </br>
			</span>
			<%= i.body %>
		</p>
		<%= link_to 'Pokaż', i %> | 
		<%= link_to 'Edytuj', edit_post_path(i) %> | 
		<%= link_to 'Usuń', i, :confirm => 'Jesteś pewny?', :method => :delete %></div>

		<% end %>
	</div>
</div>